[package]
name = "tanki"
version = "0.0.1"
authors = [ "Georgiy Shevoroshkin <gshevoroshkin@proton.me>" ]
license = "The Happy Bunny License (Modified MIT License)"
description = ""
repository = "https://github.com/omega-800/tanki.git"
categories = [ "" ]
keywords = [ "plot", "graph" ]
entrypoint = "lib/main.typ"
compiler = "0.14.0"
exclude = [ "examples/*" ]
